steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "NEXTAUTH_SECRET=${_NEXTAUTH_SECRET}" >> .env
        echo "DATABASE_URL=${_DATABASE_URL}" >> .env
        docker build \
          --build-arg NEXTAUTH_SECRET=${_NEXTAUTH_SECRET} \
          --build-arg DATABASE_URL=${_DATABASE_URL} \
          -f Dockerfile -t gcr.io/$PROJECT_ID/next-template:$COMMIT_SHA .

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/next-template:$COMMIT_SHA"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "next-template"
      - "--image"
      - "gcr.io/$PROJECT_ID/next-template:$COMMIT_SHA"
      - "--region"
      - "asia-northeast1"
      - "--allow-unauthenticated"
      - "--set-env-vars"
      - "NEXTAUTH_SECRET=${_NEXTAUTH_SECRET},DATABASE_URL=${_DATABASE_URL}"

  - name: "node:20-alpine"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
        chmod +x cloud_sql_proxy
        ./cloud_sql_proxy -instances=${_CLOUD_SQL_CONNECTION_NAME}=tcp:3306 &
        DATABASE_URL=${_MIGRATION_DATABASE_URL} npx prisma migrate deploy

images:
  - "gcr.io/$PROJECT_ID/next-template:$COMMIT_SHA"
timeout: 900s

options:
  logging: CLOUD_LOGGING_ONLY
